### ISSUE TITLE
study area

### ISSUE THREAD

**Issue by KevCaz** [inSilecoInc/shinySpatialApp#7]
Add an optional input: “study area” in addition to “search area” (in addition to the
current search area input).

This should help users visualize a given area on the map.

**Comment by david-beauchesne** [comment]
@KevCaz cella-là je ne la comprends pas, considérant qu'il n'y a pas de terme "search area" dans l'appli

**Comment by david-beauchesne** [comment]
@KevCaz I added an option to modify the map view as a function of selected geometries. Since this comment came with: 

> This should help users visualize a given area on the map.

I would be curious to know whether that meets their need before adding another tab to search the map even more. If it<s only a question of zooming into a study area, they could now achieve this by importing the study area as a geom and zooming on it in the validate tab. 

If it's to include the study area in the report, then indeed we will need to add an addition tab or option to allow them to categories different types of geoms.
